import Head from 'next/head';
import Main from './main';

export default function Home() {
    return (
        <div className="bg-neutral-900 flex-1 min-h-[100vh]">
            <Head>
                <title>Lucky Shoes</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main />
        </div>
    );
}
